version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    command:
      - start
      - --https-port=8443
    environment:

      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/keycloak.p12
      KC_HTTPS_KEY_STORE_PASSWORD: changeit
      
    ports:
      - "8443:8443"
    volumes:
      - ./certs/keycloak.p12:/opt/keycloak/conf/keycloak.p12

  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/hr-app
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hrdb
      SPRING_DATASOURCE_USERNAME: hruser
      SPRING_DATASOURCE_PASSWORD: hrpass
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - keycloak
  
  angular-app:
    build:
      context: ../frontend/hr-app
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
